/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VentasCorporativasRouteImport } from './routes/ventas-corporativas'
import { Route as TiendaRouteImport } from './routes/tienda'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResultadoPagoRouteImport } from './routes/resultado-pago'
import { Route as ProductoDeLaSemanaRouteImport } from './routes/producto-de-la-semana'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as MiCuentaRouteImport } from './routes/mi-cuenta'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriasRouteImport } from './routes/categorias'
import { Route as CatalogoAllforallDotpdfRouteImport } from './routes/catalogo-allforall[.]pdf'
import { Route as CarritoRouteImport } from './routes/carrito'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DistribuidoresIndexRouteImport } from './routes/distribuidores.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProductoSlugRouteImport } from './routes/producto.$slug'
import { Route as DistribuidoresRegistroRouteImport } from './routes/distribuidores.registro'
import { Route as DistribuidoresPortalRouteImport } from './routes/distribuidores.portal'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminMarcasRouteImport } from './routes/admin.marcas'
import { Route as AdminGeneradorFichasRouteImport } from './routes/admin.generador-fichas'
import { Route as AdminBlogGeneratorRouteImport } from './routes/admin.blog-generator'
import { Route as DistribuidoresPortalIndexRouteImport } from './routes/distribuidores.portal.index'
import { Route as DistribuidoresPortalPedidosRouteImport } from './routes/distribuidores.portal.pedidos'
import { Route as DistribuidoresPortalCatalogoRouteImport } from './routes/distribuidores.portal.catalogo'
import { Route as ApiPublicOpenpayWebhookRouteImport } from './routes/api/public/openpay-webhook'
import { Route as ApiPublicMercadopagoWebhookRouteImport } from './routes/api/public/mercadopago-webhook'
import { Route as ApiPublicAddiWebhookRouteImport } from './routes/api/public/addi-webhook'
import { Route as ApiOpenpayStoreChargeRouteImport } from './routes/api/openpay/store-charge'
import { Route as ApiOpenpayStatusRouteImport } from './routes/api/openpay/status'
import { Route as ApiOpenpayPublicConfigRouteImport } from './routes/api/openpay/public-config'
import { Route as ApiOpenpayPseRouteImport } from './routes/api/openpay/pse'
import { Route as ApiOpenpayDiagnosticoRouteImport } from './routes/api/openpay/diagnostico'
import { Route as ApiOpenpayCardRedirectRouteImport } from './routes/api/openpay/card-redirect'
import { Route as ApiOpenpayCardChargeRouteImport } from './routes/api/openpay/card-charge'
import { Route as ApiOpenpayBrebQrRouteImport } from './routes/api/openpay/breb-qr'
import { Route as ApiOpenpayBanksRouteImport } from './routes/api/openpay/banks'
import { Route as ApiAddiConfigRouteImport } from './routes/api/addi/config'

const VentasCorporativasRoute = VentasCorporativasRouteImport.update({
  id: '/ventas-corporativas',
  path: '/ventas-corporativas',
  getParentRoute: () => rootRouteImport,
} as any)
const TiendaRoute = TiendaRouteImport.update({
  id: '/tienda',
  path: '/tienda',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultadoPagoRoute = ResultadoPagoRouteImport.update({
  id: '/resultado-pago',
  path: '/resultado-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoDeLaSemanaRoute = ProductoDeLaSemanaRouteImport.update({
  id: '/producto-de-la-semana',
  path: '/producto-de-la-semana',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const MiCuentaRoute = MiCuentaRouteImport.update({
  id: '/mi-cuenta',
  path: '/mi-cuenta',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriasRoute = CategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogoAllforallDotpdfRoute = CatalogoAllforallDotpdfRouteImport.update({
  id: '/catalogo-allforall.pdf',
  path: '/catalogo-allforall.pdf',
  getParentRoute: () => rootRouteImport,
} as any)
const CarritoRoute = CarritoRouteImport.update({
  id: '/carrito',
  path: '/carrito',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidoresIndexRoute = DistribuidoresIndexRouteImport.update({
  id: '/distribuidores/',
  path: '/distribuidores/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProductoSlugRoute = ProductoSlugRouteImport.update({
  id: '/producto/$slug',
  path: '/producto/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidoresRegistroRoute = DistribuidoresRegistroRouteImport.update({
  id: '/distribuidores/registro',
  path: '/distribuidores/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribuidoresPortalRoute = DistribuidoresPortalRouteImport.update({
  id: '/distribuidores/portal',
  path: '/distribuidores/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AdminMarcasRoute = AdminMarcasRouteImport.update({
  id: '/marcas',
  path: '/marcas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeneradorFichasRoute = AdminGeneradorFichasRouteImport.update({
  id: '/generador-fichas',
  path: '/generador-fichas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogGeneratorRoute = AdminBlogGeneratorRouteImport.update({
  id: '/blog-generator',
  path: '/blog-generator',
  getParentRoute: () => AdminRoute,
} as any)
const DistribuidoresPortalIndexRoute =
  DistribuidoresPortalIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DistribuidoresPortalRoute,
  } as any)
const DistribuidoresPortalPedidosRoute =
  DistribuidoresPortalPedidosRouteImport.update({
    id: '/pedidos',
    path: '/pedidos',
    getParentRoute: () => DistribuidoresPortalRoute,
  } as any)
const DistribuidoresPortalCatalogoRoute =
  DistribuidoresPortalCatalogoRouteImport.update({
    id: '/catalogo',
    path: '/catalogo',
    getParentRoute: () => DistribuidoresPortalRoute,
  } as any)
const ApiPublicOpenpayWebhookRoute = ApiPublicOpenpayWebhookRouteImport.update({
  id: '/api/public/openpay-webhook',
  path: '/api/public/openpay-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoWebhookRoute =
  ApiPublicMercadopagoWebhookRouteImport.update({
    id: '/api/public/mercadopago-webhook',
    path: '/api/public/mercadopago-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAddiWebhookRoute = ApiPublicAddiWebhookRouteImport.update({
  id: '/api/public/addi-webhook',
  path: '/api/public/addi-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenpayStoreChargeRoute = ApiOpenpayStoreChargeRouteImport.update({
  id: '/api/openpay/store-charge',
  path: '/api/openpay/store-charge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenpayStatusRoute = ApiOpenpayStatusRouteImport.update({
  id: '/api/openpay/status',
  path: '/api/openpay/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenpayPublicConfigRoute = ApiOpenpayPublicConfigRouteImport.update({
  id: '/api/openpay/public-config',
  path: '/api/openpay/public-config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenpayPseRoute = ApiOpenpayPseRouteImport.update({
  id: '/api/openpay/pse',
  path: '/api/openpay/pse',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenpayDiagnosticoRoute = ApiOpenpayDiagnosticoRouteImport.update({
  id: '/api/openpay/diagnostico',
  path: '/api/openpay/diagnostico',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenpayCardRedirectRoute = ApiOpenpayCardRedirectRouteImport.update({
  id: '/api/openpay/card-redirect',
  path: '/api/openpay/card-redirect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenpayCardChargeRoute = ApiOpenpayCardChargeRouteImport.update({
  id: '/api/openpay/card-charge',
  path: '/api/openpay/card-charge',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenpayBrebQrRoute = ApiOpenpayBrebQrRouteImport.update({
  id: '/api/openpay/breb-qr',
  path: '/api/openpay/breb-qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOpenpayBanksRoute = ApiOpenpayBanksRouteImport.update({
  id: '/api/openpay/banks',
  path: '/api/openpay/banks',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAddiConfigRoute = ApiAddiConfigRouteImport.update({
  id: '/api/addi/config',
  path: '/api/addi/config',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo-allforall.pdf': typeof CatalogoAllforallDotpdfRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/legal': typeof LegalRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/nosotros': typeof NosotrosRoute
  '/producto-de-la-semana': typeof ProductoDeLaSemanaRoute
  '/resultado-pago': typeof ResultadoPagoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/ventas-corporativas': typeof VentasCorporativasRoute
  '/admin/blog-generator': typeof AdminBlogGeneratorRoute
  '/admin/generador-fichas': typeof AdminGeneradorFichasRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/distribuidores/portal': typeof DistribuidoresPortalRouteWithChildren
  '/distribuidores/registro': typeof DistribuidoresRegistroRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/distribuidores/': typeof DistribuidoresIndexRoute
  '/api/addi/config': typeof ApiAddiConfigRoute
  '/api/openpay/banks': typeof ApiOpenpayBanksRoute
  '/api/openpay/breb-qr': typeof ApiOpenpayBrebQrRoute
  '/api/openpay/card-charge': typeof ApiOpenpayCardChargeRoute
  '/api/openpay/card-redirect': typeof ApiOpenpayCardRedirectRoute
  '/api/openpay/diagnostico': typeof ApiOpenpayDiagnosticoRoute
  '/api/openpay/pse': typeof ApiOpenpayPseRoute
  '/api/openpay/public-config': typeof ApiOpenpayPublicConfigRoute
  '/api/openpay/status': typeof ApiOpenpayStatusRoute
  '/api/openpay/store-charge': typeof ApiOpenpayStoreChargeRoute
  '/api/public/addi-webhook': typeof ApiPublicAddiWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/openpay-webhook': typeof ApiPublicOpenpayWebhookRoute
  '/distribuidores/portal/catalogo': typeof DistribuidoresPortalCatalogoRoute
  '/distribuidores/portal/pedidos': typeof DistribuidoresPortalPedidosRoute
  '/distribuidores/portal/': typeof DistribuidoresPortalIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo-allforall.pdf': typeof CatalogoAllforallDotpdfRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/legal': typeof LegalRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/nosotros': typeof NosotrosRoute
  '/producto-de-la-semana': typeof ProductoDeLaSemanaRoute
  '/resultado-pago': typeof ResultadoPagoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/ventas-corporativas': typeof VentasCorporativasRoute
  '/admin/blog-generator': typeof AdminBlogGeneratorRoute
  '/admin/generador-fichas': typeof AdminGeneradorFichasRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/distribuidores/registro': typeof DistribuidoresRegistroRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin': typeof AdminIndexRoute
  '/distribuidores': typeof DistribuidoresIndexRoute
  '/api/addi/config': typeof ApiAddiConfigRoute
  '/api/openpay/banks': typeof ApiOpenpayBanksRoute
  '/api/openpay/breb-qr': typeof ApiOpenpayBrebQrRoute
  '/api/openpay/card-charge': typeof ApiOpenpayCardChargeRoute
  '/api/openpay/card-redirect': typeof ApiOpenpayCardRedirectRoute
  '/api/openpay/diagnostico': typeof ApiOpenpayDiagnosticoRoute
  '/api/openpay/pse': typeof ApiOpenpayPseRoute
  '/api/openpay/public-config': typeof ApiOpenpayPublicConfigRoute
  '/api/openpay/status': typeof ApiOpenpayStatusRoute
  '/api/openpay/store-charge': typeof ApiOpenpayStoreChargeRoute
  '/api/public/addi-webhook': typeof ApiPublicAddiWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/openpay-webhook': typeof ApiPublicOpenpayWebhookRoute
  '/distribuidores/portal/catalogo': typeof DistribuidoresPortalCatalogoRoute
  '/distribuidores/portal/pedidos': typeof DistribuidoresPortalPedidosRoute
  '/distribuidores/portal': typeof DistribuidoresPortalIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRouteWithChildren
  '/carrito': typeof CarritoRoute
  '/catalogo-allforall.pdf': typeof CatalogoAllforallDotpdfRoute
  '/categorias': typeof CategoriasRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/legal': typeof LegalRoute
  '/mi-cuenta': typeof MiCuentaRoute
  '/nosotros': typeof NosotrosRoute
  '/producto-de-la-semana': typeof ProductoDeLaSemanaRoute
  '/resultado-pago': typeof ResultadoPagoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tienda': typeof TiendaRoute
  '/ventas-corporativas': typeof VentasCorporativasRoute
  '/admin/blog-generator': typeof AdminBlogGeneratorRoute
  '/admin/generador-fichas': typeof AdminGeneradorFichasRoute
  '/admin/marcas': typeof AdminMarcasRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/distribuidores/portal': typeof DistribuidoresPortalRouteWithChildren
  '/distribuidores/registro': typeof DistribuidoresRegistroRoute
  '/producto/$slug': typeof ProductoSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/distribuidores/': typeof DistribuidoresIndexRoute
  '/api/addi/config': typeof ApiAddiConfigRoute
  '/api/openpay/banks': typeof ApiOpenpayBanksRoute
  '/api/openpay/breb-qr': typeof ApiOpenpayBrebQrRoute
  '/api/openpay/card-charge': typeof ApiOpenpayCardChargeRoute
  '/api/openpay/card-redirect': typeof ApiOpenpayCardRedirectRoute
  '/api/openpay/diagnostico': typeof ApiOpenpayDiagnosticoRoute
  '/api/openpay/pse': typeof ApiOpenpayPseRoute
  '/api/openpay/public-config': typeof ApiOpenpayPublicConfigRoute
  '/api/openpay/status': typeof ApiOpenpayStatusRoute
  '/api/openpay/store-charge': typeof ApiOpenpayStoreChargeRoute
  '/api/public/addi-webhook': typeof ApiPublicAddiWebhookRoute
  '/api/public/mercadopago-webhook': typeof ApiPublicMercadopagoWebhookRoute
  '/api/public/openpay-webhook': typeof ApiPublicOpenpayWebhookRoute
  '/distribuidores/portal/catalogo': typeof DistribuidoresPortalCatalogoRoute
  '/distribuidores/portal/pedidos': typeof DistribuidoresPortalPedidosRoute
  '/distribuidores/portal/': typeof DistribuidoresPortalIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/carrito'
    | '/catalogo-allforall.pdf'
    | '/categorias'
    | '/checkout'
    | '/contacto'
    | '/legal'
    | '/mi-cuenta'
    | '/nosotros'
    | '/producto-de-la-semana'
    | '/resultado-pago'
    | '/sitemap.xml'
    | '/tienda'
    | '/ventas-corporativas'
    | '/admin/blog-generator'
    | '/admin/generador-fichas'
    | '/admin/marcas'
    | '/blog/$slug'
    | '/distribuidores/portal'
    | '/distribuidores/registro'
    | '/producto/$slug'
    | '/admin/'
    | '/distribuidores/'
    | '/api/addi/config'
    | '/api/openpay/banks'
    | '/api/openpay/breb-qr'
    | '/api/openpay/card-charge'
    | '/api/openpay/card-redirect'
    | '/api/openpay/diagnostico'
    | '/api/openpay/pse'
    | '/api/openpay/public-config'
    | '/api/openpay/status'
    | '/api/openpay/store-charge'
    | '/api/public/addi-webhook'
    | '/api/public/mercadopago-webhook'
    | '/api/public/openpay-webhook'
    | '/distribuidores/portal/catalogo'
    | '/distribuidores/portal/pedidos'
    | '/distribuidores/portal/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/blog'
    | '/carrito'
    | '/catalogo-allforall.pdf'
    | '/categorias'
    | '/checkout'
    | '/contacto'
    | '/legal'
    | '/mi-cuenta'
    | '/nosotros'
    | '/producto-de-la-semana'
    | '/resultado-pago'
    | '/sitemap.xml'
    | '/tienda'
    | '/ventas-corporativas'
    | '/admin/blog-generator'
    | '/admin/generador-fichas'
    | '/admin/marcas'
    | '/blog/$slug'
    | '/distribuidores/registro'
    | '/producto/$slug'
    | '/admin'
    | '/distribuidores'
    | '/api/addi/config'
    | '/api/openpay/banks'
    | '/api/openpay/breb-qr'
    | '/api/openpay/card-charge'
    | '/api/openpay/card-redirect'
    | '/api/openpay/diagnostico'
    | '/api/openpay/pse'
    | '/api/openpay/public-config'
    | '/api/openpay/status'
    | '/api/openpay/store-charge'
    | '/api/public/addi-webhook'
    | '/api/public/mercadopago-webhook'
    | '/api/public/openpay-webhook'
    | '/distribuidores/portal/catalogo'
    | '/distribuidores/portal/pedidos'
    | '/distribuidores/portal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/blog'
    | '/carrito'
    | '/catalogo-allforall.pdf'
    | '/categorias'
    | '/checkout'
    | '/contacto'
    | '/legal'
    | '/mi-cuenta'
    | '/nosotros'
    | '/producto-de-la-semana'
    | '/resultado-pago'
    | '/sitemap.xml'
    | '/tienda'
    | '/ventas-corporativas'
    | '/admin/blog-generator'
    | '/admin/generador-fichas'
    | '/admin/marcas'
    | '/blog/$slug'
    | '/distribuidores/portal'
    | '/distribuidores/registro'
    | '/producto/$slug'
    | '/admin/'
    | '/distribuidores/'
    | '/api/addi/config'
    | '/api/openpay/banks'
    | '/api/openpay/breb-qr'
    | '/api/openpay/card-charge'
    | '/api/openpay/card-redirect'
    | '/api/openpay/diagnostico'
    | '/api/openpay/pse'
    | '/api/openpay/public-config'
    | '/api/openpay/status'
    | '/api/openpay/store-charge'
    | '/api/public/addi-webhook'
    | '/api/public/mercadopago-webhook'
    | '/api/public/openpay-webhook'
    | '/distribuidores/portal/catalogo'
    | '/distribuidores/portal/pedidos'
    | '/distribuidores/portal/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRouteWithChildren
  CarritoRoute: typeof CarritoRoute
  CatalogoAllforallDotpdfRoute: typeof CatalogoAllforallDotpdfRoute
  CategoriasRoute: typeof CategoriasRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  LegalRoute: typeof LegalRoute
  MiCuentaRoute: typeof MiCuentaRoute
  NosotrosRoute: typeof NosotrosRoute
  ProductoDeLaSemanaRoute: typeof ProductoDeLaSemanaRoute
  ResultadoPagoRoute: typeof ResultadoPagoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TiendaRoute: typeof TiendaRoute
  VentasCorporativasRoute: typeof VentasCorporativasRoute
  DistribuidoresPortalRoute: typeof DistribuidoresPortalRouteWithChildren
  DistribuidoresRegistroRoute: typeof DistribuidoresRegistroRoute
  ProductoSlugRoute: typeof ProductoSlugRoute
  DistribuidoresIndexRoute: typeof DistribuidoresIndexRoute
  ApiAddiConfigRoute: typeof ApiAddiConfigRoute
  ApiOpenpayBanksRoute: typeof ApiOpenpayBanksRoute
  ApiOpenpayBrebQrRoute: typeof ApiOpenpayBrebQrRoute
  ApiOpenpayCardChargeRoute: typeof ApiOpenpayCardChargeRoute
  ApiOpenpayCardRedirectRoute: typeof ApiOpenpayCardRedirectRoute
  ApiOpenpayDiagnosticoRoute: typeof ApiOpenpayDiagnosticoRoute
  ApiOpenpayPseRoute: typeof ApiOpenpayPseRoute
  ApiOpenpayPublicConfigRoute: typeof ApiOpenpayPublicConfigRoute
  ApiOpenpayStatusRoute: typeof ApiOpenpayStatusRoute
  ApiOpenpayStoreChargeRoute: typeof ApiOpenpayStoreChargeRoute
  ApiPublicAddiWebhookRoute: typeof ApiPublicAddiWebhookRoute
  ApiPublicMercadopagoWebhookRoute: typeof ApiPublicMercadopagoWebhookRoute
  ApiPublicOpenpayWebhookRoute: typeof ApiPublicOpenpayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ventas-corporativas': {
      id: '/ventas-corporativas'
      path: '/ventas-corporativas'
      fullPath: '/ventas-corporativas'
      preLoaderRoute: typeof VentasCorporativasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tienda': {
      id: '/tienda'
      path: '/tienda'
      fullPath: '/tienda'
      preLoaderRoute: typeof TiendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resultado-pago': {
      id: '/resultado-pago'
      path: '/resultado-pago'
      fullPath: '/resultado-pago'
      preLoaderRoute: typeof ResultadoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto-de-la-semana': {
      id: '/producto-de-la-semana'
      path: '/producto-de-la-semana'
      fullPath: '/producto-de-la-semana'
      preLoaderRoute: typeof ProductoDeLaSemanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mi-cuenta': {
      id: '/mi-cuenta'
      path: '/mi-cuenta'
      fullPath: '/mi-cuenta'
      preLoaderRoute: typeof MiCuentaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categorias': {
      id: '/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof CategoriasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalogo-allforall.pdf': {
      id: '/catalogo-allforall.pdf'
      path: '/catalogo-allforall.pdf'
      fullPath: '/catalogo-allforall.pdf'
      preLoaderRoute: typeof CatalogoAllforallDotpdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrito': {
      id: '/carrito'
      path: '/carrito'
      fullPath: '/carrito'
      preLoaderRoute: typeof CarritoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidores/': {
      id: '/distribuidores/'
      path: '/distribuidores'
      fullPath: '/distribuidores/'
      preLoaderRoute: typeof DistribuidoresIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/producto/$slug': {
      id: '/producto/$slug'
      path: '/producto/$slug'
      fullPath: '/producto/$slug'
      preLoaderRoute: typeof ProductoSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidores/registro': {
      id: '/distribuidores/registro'
      path: '/distribuidores/registro'
      fullPath: '/distribuidores/registro'
      preLoaderRoute: typeof DistribuidoresRegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribuidores/portal': {
      id: '/distribuidores/portal'
      path: '/distribuidores/portal'
      fullPath: '/distribuidores/portal'
      preLoaderRoute: typeof DistribuidoresPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/admin/marcas': {
      id: '/admin/marcas'
      path: '/marcas'
      fullPath: '/admin/marcas'
      preLoaderRoute: typeof AdminMarcasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/generador-fichas': {
      id: '/admin/generador-fichas'
      path: '/generador-fichas'
      fullPath: '/admin/generador-fichas'
      preLoaderRoute: typeof AdminGeneradorFichasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog-generator': {
      id: '/admin/blog-generator'
      path: '/blog-generator'
      fullPath: '/admin/blog-generator'
      preLoaderRoute: typeof AdminBlogGeneratorRouteImport
      parentRoute: typeof AdminRoute
    }
    '/distribuidores/portal/': {
      id: '/distribuidores/portal/'
      path: '/'
      fullPath: '/distribuidores/portal/'
      preLoaderRoute: typeof DistribuidoresPortalIndexRouteImport
      parentRoute: typeof DistribuidoresPortalRoute
    }
    '/distribuidores/portal/pedidos': {
      id: '/distribuidores/portal/pedidos'
      path: '/pedidos'
      fullPath: '/distribuidores/portal/pedidos'
      preLoaderRoute: typeof DistribuidoresPortalPedidosRouteImport
      parentRoute: typeof DistribuidoresPortalRoute
    }
    '/distribuidores/portal/catalogo': {
      id: '/distribuidores/portal/catalogo'
      path: '/catalogo'
      fullPath: '/distribuidores/portal/catalogo'
      preLoaderRoute: typeof DistribuidoresPortalCatalogoRouteImport
      parentRoute: typeof DistribuidoresPortalRoute
    }
    '/api/public/openpay-webhook': {
      id: '/api/public/openpay-webhook'
      path: '/api/public/openpay-webhook'
      fullPath: '/api/public/openpay-webhook'
      preLoaderRoute: typeof ApiPublicOpenpayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago-webhook': {
      id: '/api/public/mercadopago-webhook'
      path: '/api/public/mercadopago-webhook'
      fullPath: '/api/public/mercadopago-webhook'
      preLoaderRoute: typeof ApiPublicMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/addi-webhook': {
      id: '/api/public/addi-webhook'
      path: '/api/public/addi-webhook'
      fullPath: '/api/public/addi-webhook'
      preLoaderRoute: typeof ApiPublicAddiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openpay/store-charge': {
      id: '/api/openpay/store-charge'
      path: '/api/openpay/store-charge'
      fullPath: '/api/openpay/store-charge'
      preLoaderRoute: typeof ApiOpenpayStoreChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openpay/status': {
      id: '/api/openpay/status'
      path: '/api/openpay/status'
      fullPath: '/api/openpay/status'
      preLoaderRoute: typeof ApiOpenpayStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openpay/public-config': {
      id: '/api/openpay/public-config'
      path: '/api/openpay/public-config'
      fullPath: '/api/openpay/public-config'
      preLoaderRoute: typeof ApiOpenpayPublicConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openpay/pse': {
      id: '/api/openpay/pse'
      path: '/api/openpay/pse'
      fullPath: '/api/openpay/pse'
      preLoaderRoute: typeof ApiOpenpayPseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openpay/diagnostico': {
      id: '/api/openpay/diagnostico'
      path: '/api/openpay/diagnostico'
      fullPath: '/api/openpay/diagnostico'
      preLoaderRoute: typeof ApiOpenpayDiagnosticoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openpay/card-redirect': {
      id: '/api/openpay/card-redirect'
      path: '/api/openpay/card-redirect'
      fullPath: '/api/openpay/card-redirect'
      preLoaderRoute: typeof ApiOpenpayCardRedirectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openpay/card-charge': {
      id: '/api/openpay/card-charge'
      path: '/api/openpay/card-charge'
      fullPath: '/api/openpay/card-charge'
      preLoaderRoute: typeof ApiOpenpayCardChargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openpay/breb-qr': {
      id: '/api/openpay/breb-qr'
      path: '/api/openpay/breb-qr'
      fullPath: '/api/openpay/breb-qr'
      preLoaderRoute: typeof ApiOpenpayBrebQrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/openpay/banks': {
      id: '/api/openpay/banks'
      path: '/api/openpay/banks'
      fullPath: '/api/openpay/banks'
      preLoaderRoute: typeof ApiOpenpayBanksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/addi/config': {
      id: '/api/addi/config'
      path: '/api/addi/config'
      fullPath: '/api/addi/config'
      preLoaderRoute: typeof ApiAddiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminBlogGeneratorRoute: typeof AdminBlogGeneratorRoute
  AdminGeneradorFichasRoute: typeof AdminGeneradorFichasRoute
  AdminMarcasRoute: typeof AdminMarcasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBlogGeneratorRoute: AdminBlogGeneratorRoute,
  AdminGeneradorFichasRoute: AdminGeneradorFichasRoute,
  AdminMarcasRoute: AdminMarcasRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DistribuidoresPortalRouteChildren {
  DistribuidoresPortalCatalogoRoute: typeof DistribuidoresPortalCatalogoRoute
  DistribuidoresPortalPedidosRoute: typeof DistribuidoresPortalPedidosRoute
  DistribuidoresPortalIndexRoute: typeof DistribuidoresPortalIndexRoute
}

const DistribuidoresPortalRouteChildren: DistribuidoresPortalRouteChildren = {
  DistribuidoresPortalCatalogoRoute: DistribuidoresPortalCatalogoRoute,
  DistribuidoresPortalPedidosRoute: DistribuidoresPortalPedidosRoute,
  DistribuidoresPortalIndexRoute: DistribuidoresPortalIndexRoute,
}

const DistribuidoresPortalRouteWithChildren =
  DistribuidoresPortalRoute._addFileChildren(DistribuidoresPortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRouteWithChildren,
  CarritoRoute: CarritoRoute,
  CatalogoAllforallDotpdfRoute: CatalogoAllforallDotpdfRoute,
  CategoriasRoute: CategoriasRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  LegalRoute: LegalRoute,
  MiCuentaRoute: MiCuentaRoute,
  NosotrosRoute: NosotrosRoute,
  ProductoDeLaSemanaRoute: ProductoDeLaSemanaRoute,
  ResultadoPagoRoute: ResultadoPagoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TiendaRoute: TiendaRoute,
  VentasCorporativasRoute: VentasCorporativasRoute,
  DistribuidoresPortalRoute: DistribuidoresPortalRouteWithChildren,
  DistribuidoresRegistroRoute: DistribuidoresRegistroRoute,
  ProductoSlugRoute: ProductoSlugRoute,
  DistribuidoresIndexRoute: DistribuidoresIndexRoute,
  ApiAddiConfigRoute: ApiAddiConfigRoute,
  ApiOpenpayBanksRoute: ApiOpenpayBanksRoute,
  ApiOpenpayBrebQrRoute: ApiOpenpayBrebQrRoute,
  ApiOpenpayCardChargeRoute: ApiOpenpayCardChargeRoute,
  ApiOpenpayCardRedirectRoute: ApiOpenpayCardRedirectRoute,
  ApiOpenpayDiagnosticoRoute: ApiOpenpayDiagnosticoRoute,
  ApiOpenpayPseRoute: ApiOpenpayPseRoute,
  ApiOpenpayPublicConfigRoute: ApiOpenpayPublicConfigRoute,
  ApiOpenpayStatusRoute: ApiOpenpayStatusRoute,
  ApiOpenpayStoreChargeRoute: ApiOpenpayStoreChargeRoute,
  ApiPublicAddiWebhookRoute: ApiPublicAddiWebhookRoute,
  ApiPublicMercadopagoWebhookRoute: ApiPublicMercadopagoWebhookRoute,
  ApiPublicOpenpayWebhookRoute: ApiPublicOpenpayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
